### ISSUE TITLE
clear audio buffer

### ISSUE THREAD

**Issue by jaime1988** [Burgestrand/hallon-openal#2]
Hi again,

Now the stop works perfect. My problem now is that when I execute this:

``` ruby
player.play(track2)
sleep(5)
player.stop
player.play(track3)
```

It starts playing track2, after 5 secs it stops. And when you try to play track3, it sounds 1-2 more seconds from track2 and then track3 starts. Is there any way to clear the buffers or the object?

Thanks for all. You are doing an excellent job.

**Comment by Burgestrand** [comment]
Hm.

After the audio source has stopped, all the buffers are removed from it. When playing again, a non-attached buffer is found, filled with data and attached for the source to play. I’m not sure from where this stray audio is coming from. I tried rewinding the source before attaching data to it, but with no success. I also ran into issues with filling up the buffers with data, which I’m not sure of why.

I didn’t manage to solve the issue today. I’ll take another look at it tomorrow, or possibly thursday.

PS: Thanks for the bug reports. It’s nice to iron out some issues :)

**Comment by Burgestrand** [comment]
I haven't been able to look at it yet, but I believe destroying the buffers and regenerating them later might help.

I'm not sure this issue is entirely the fault of Hallon::OpenAl. Might have some issues on the Hallon side as well, given that the audio callbacks might fire even after stopping the streaming (result of the way you have to handle them in Ruby).

**Comment by jaime1988** [comment]
I have been trying something and there is a problem, if you do this

``` ruby

player.play
puts 'start playin'
sleep(4)
puts 'stop playing'
player.stop
sleep(4)
puts 'restart playing'
player.load(track)#if you try to load another song the result is the same
player.play
```

It gives the next error: 
/Users/jaime/.rvm/gems/ruby-1.9.3-p125/gems/hallon-0.16.0/lib/hallon/player.rb:55:in `stream': OpenAL error: 40964 (buffer data) (RuntimeError)
    from /Users/jaime/.rvm/gems/ruby-1.9.3-p125/gems/hallon-0.16.0/lib/hallon/player.rb:55:in`block in initialize'

And if you don't load another song, it doesn't give an error but nothing sounds

How can the buffers be controlled from ruby?

**Comment by Burgestrand** [comment]
I’ve gotten the error you receive there as well. It might very well be that the buffer is full, and as such cannot take more data. If that is the case, it’d explain the case where you play some old data before playing the new data. It should also be solved by actually destroying the buffers on stop and re-creating them just in time for playback, like I’ve mentioned earlier.

As far as controlling the buffers from Ruby you cannot do that. Hallon::OpenAL was written in a minimal amount of time, for a minimal API. Using the OpenAL API is not nice, and the documentation is not easily consumed either. I’ve been working on writing drivers with some other backend (CoreAudio for one) to ease the pain of maintaining it, but have yet to succeed in a stable fashion (actually, this driver is not very stable either).

When it comes to the player.stop => player.play it’s to be expected. If you stop, libspotify unloads the currently loaded track. In order to play anything, you need to load it up first. If you want to pause playback, and then continue again without loading a new track use Player#pause instead. The player could keep track of the currently loaded song and raise an error when none is loaded, and I’ve been thinking about a rewrite for it for a while (which would also make it easier to implement support for knowing the current track position, for example).

**Comment by Burgestrand** [comment]
Turns out it’s not as simple destroying/recreating the buffers. Even if one would do it on stop, thread-safety issues are of concern. Even if the player is not currently playing, it might be receiving and buffering audio. In essence, one will probably need a lock around the internal data of Hallon::OpenAL, which requires a bit of refactoring (which would be nice to do anyway).

On another note I’ve been working on another issue for Hallon for refactoring the Player (see Burgestrand/Hallon#110). It will bring much-needed changes to the driver API, so I’ll wait with refactoring the OpenAL driver until I know exactly what those changes imply. In addition, the changes to the Player should help with this issue as well (and I might not need the above mentioned lock in the end).

**Comment by jaime1988** [comment]
Ok, I will be watching the repo for future changes. 

Thanks for all! This is very useful

**Comment by Burgestrand** [comment]
To bring an update to this issue: I’ve got a new idea for the Player that I’m in the process of writing, that I expect to be about a days work or two. However, I’m also at the final stages of my bachelor thesis, so Hallon will have to wait a bit more in favor of schoolwork for this week.

**Comment by jaime1988** [comment]
Very good news then :D good luck with the thesis!

**Comment by Burgestrand** [comment]
@jaime1988 Oh, wow, I am _so_ sorry! I completely forgot about this issue once summer set in! My ideas for the Player refactor in Hallon are promising, but are kind of unrelated to this issue in reality (those changes can come later).

Now, to document my progress on this issue I’ll write my current status here. The issue in itself is a tricky one, especially since we’ll have to deal with thread synchronization on C-level, and the order of operations is very important. To work out a possible solution for this issue I drew lots of tables [and little arrows, visualizing the flow](http://instagram.com/p/MJmFJOhs0p/). However, even after that I was not done. Had to do another session of doodling.

Either way, the actual stream block in the audio driver will need to take these steps.
1. wait if not currently playing audio (not sure if this step is _really_ needed)
2. retrieve audio frames from Hallon through callback
3. restart from point 1 if no frames, format has changed
4. looping until we have an audio buffer, do:
   1. lock the audio source lock
   2. if the audio source has no attached buffers, create a new one
   3. if the audio source has attached buffers, find an empty one
   4. if the audio source has attached buffers, but no empty ones, unlock and restart from 4.1 (make sure somehow another thread can get lock if waiting)
5. fill up buffer with audio and attach it to source
6. unlock the audio source lock
7. force playback if OpenAL is not in AL_PLAYING, but we should be playing

Stopping the audio is as simple as:
1. lock audio source lock
2. stop audio playback
3. remove attached buffers
4. destroy attached buffers
5. unlock audio source lock

I think the above strategy is a good one. Just needs to be implemented. Slightly worried about point 4.4 in streamer steps. There is a risk of crazy locking if somebody tries to stop audio playing but the stop method never has time to get the audio source lock because the streamer is constantly stealing it.

**Comment by Burgestrand** [comment]
From the solution of #5, it appears this bug has also been fixed.
