### ISSUE TITLE
Unable to start new song after stopping

### ISSUE THREAD

**Issue by swerner** [Burgestrand/hallon-openal#5]
I'm pretty sure this goes here rather than regular Hallon. I may be doing something wrong, but I'm unable to get the player to start playing a new song after stopping another. 

The code I'm trying to use is here: 
https://github.com/swerner/rubus-jukebox/blob/master/server/lib/rubus/jukebox.rb
Just calling play with one track =>  works correctly and starts playing
Call stop => stops the track correctly
Call play with another track => does nothing

I traced it through hallon and it appears its making all the method calls, and the second Spotify play call fires correctly. I also attempted to just destroy the player and create a new one on play, but that gave me a buffer error. I'm not too familiar with Ruby C extensions or I'd have tried more things in hallon-openal.  Let me know if I can do anything else to help track this down.

**Comment by Burgestrand** [comment]
Hi! I’ve been away on a snowboarding trip for the past days, and now I’m down with pneumonia. I just called in to say I’ve seen the issue, but can’t research it at this moment.

**Comment by swerner** [comment]
Hey, thank you for responding! No hurry, get better! I'll keep poking around to see if I can figure it out.

**Comment by Burgestrand** [comment]
I’ve managed to replicate the issue locally.

I believe hallon-openal ends up in a state where it thinks there are audio buffers (containers you fill with audio and attach to the speakers to have them play) still attached to the speakers, and it waits until the speakers have played at least one buffer so it can take it off, refill it with audio, and attach it back again. Unfortunately, since we just stopped playing, there can be no audio buffers attached. I believe this is the case because hallon-openal seems to be stuck forever waiting for an empty buffer: https://github.com/Burgestrand/hallon-openal/blob/master/ext/hallon/openal_ext.c#L238

Most likely, this is a race condition bug. If you stop playing while hallon-openal is waiting for an empty buffer, it will wait there forever. There are more race condition bugs hidden in hallon-openal because the entire design of the library is somewhat flawed.

A possible fix would be to do the checking every iteration of the loop. No idea how it behaves, or if it’s even the true cause of this issue, but it’s a start.

**Comment by Burgestrand** [comment]
I’ve put together something that fixes the issue for me. I can now successfully stop and play a new track. Please call back and tell me if it works for you once you’ve tried it @swerner. :)

**Comment by swerner** [comment]
Wow, that was fast! Can't wait to get home to try it out. Thanks!

**Comment by swerner** [comment]
Just got home to give it a shot, and it worked perfectly!

**Comment by Burgestrand** [comment]
Great stuff. :)
